version: '2.1'
services:
  web:
    depends_on:
      mysql:
        condition: service_healthy         
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
     - ./app/src:/src
     - /src/node_modules  
    ports:
       - "3000:3000"
    links:
      - mysql    
    restart: always
    
    
  mysql:
    image: mariadb
    restart: always
    ports:
     - "3307:3306"        
    environment:
      MYSQL_ROOT_PASSWORD: paraguay
      MYSQL_USER: admin
      MYSQL_DATABASE: ormdb
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=paraguay  --database=ormdb "
      interval: 10s
      timeout: 3s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password


